name: "markdownlint"
description: "Run preconfigured markdownlint with custom plugins"
runs:
  using: "composite"
  steps:
    - id: add_matcher
      shell: bash
      name: Add the matcher for markdownlint style message output
      run: "echo ::add-matcher::${{ github.action_path }}/problem-matcher.json"

    - id: install_linter
      shell: bash
      name: Install linting tool and custom rule
      run: npm ci

    - id: run_linter
      shell: bash
      name: Run linter with specific rules, on the docs/ content
      run: npm run lint -- ${{ github.workspace }}/docs/

