name: "markdown-link-check"
description: "Run preconfigured markdown-link-check"
inputs:
  markdown-directory:
    description: 'markdown directory to check links in'
    required: true
    default: ${{ github.workspace }}/docs/

runs:
  using: "composite"
  steps:
    - id: install_markdown_link_check
      shell: bash
      name: Install markdown_link_check tool
      run: cd ${{ github.action_path }} && npm ci

    - id: run_install_markdown_link_check
      shell: bash
      name: Run markdown_link_check with specific rules, on the docs/ content
      run: ${{ github.action_path }}/markdown-link-check.sh ${{ inputs.markdown-directory }} ${{ github.workspace }}
